### ISSUE TITLE
Error: Unable to connect to powermeter

### ISSUE THREAD

**Issue by TurboDuke77** [ituri/opendtu-widget#7]
I would like to use the widget without OpenDTU, as I only have the Tasmota Powermeter. I have entered the Tasmota url http://192.168.178.64/cm?cmnd=status%208 and showPowerDraw = 1. I only get the message Unable to connect to powermeter.

My powermeter displays the following under the URL in the browser: {“StatusSNS”:{“Time”:“2024-06-01T19:19:42”,“M60”:{“E_in”:2358.536,“E_out”:41.830,“Power”:307}}}

**Comment by ituri** [comment]
I'm afraid that's not really something I can provide support for, since the focus of the widget lies on OpenDTU. 

You can however try to fork and modify the script yourself. As of now, I see that your current power consumption is called `Power` whereas the script is looking for `current`. This is something you should change if you want to fork and modify the script to work for your setup.
